const MAX_CHARACTER_PAGE = 8
const CHARACTERS_PER_PAGE = 100

const BASE_POWER = 50
const BASE_MAGIC = 50
const BASE_DEFENSE = 50

const GRYFFINDOR_POWER = 90
const SLYTHERIN_POWER = 85
const HUFFLEPUFF_POWER = 75
const RAVENCLAW_POWER = 80

const HUMAN_MAGIC = 70
const HALF_GIANT_MAGIC = 88
const GIANT_MAGIC = 95
const HOUSE_ELF_MAGIC = 82
const GHOST_MAGIC = 60
const WEREWOLF_MAGIC = 91
const VAMPIRE_MAGIC = 87
const CENTAUR_MAGIC = 78

const PURE_BLOOD_DEFENSE = 90
const HALF_BLOOD_DEFENSE = 75
const MUGGLE_BORN_DEFENSE = 70
const MUGGLE_DEFENSE = 40
const SQUIB_DEFENSE = 35

const BASE_HP = 80
const RANDOM_HP_BONUS = 20

const PACK_SIZE = 4
const SPELL_COUNT = 20
const CPU_DECK_SIZE = 2

const DEFAULT_DAMAGE = 30
const CHARM_DAMAGE = 45
const CURSE_DAMAGE = 90
const HEX_DAMAGE = 65
const JINX_DAMAGE = 55
const SPELL_DAMAGE = 50
const TRANSFIGURATION_DAMAGE = 40
const COUNTER_SPELL_DAMAGE = 35
const HEALING_DAMAGE = -40

const SERVER_PORT = 3000

module.exports = {
  MAX_CHARACTER_PAGE,
  CHARACTERS_PER_PAGE,
  BASE_POWER,
  BASE_MAGIC,
  BASE_DEFENSE,
  GRYFFINDOR_POWER,
  SLYTHERIN_POWER,
  HUFFLEPUFF_POWER,
  RAVENCLAW_POWER,
  HUMAN_MAGIC,
  HALF_GIANT_MAGIC,
  GIANT_MAGIC,
  HOUSE_ELF_MAGIC,
  GHOST_MAGIC,
  WEREWOLF_MAGIC,
  VAMPIRE_MAGIC,
  CENTAUR_MAGIC,
  PURE_BLOOD_DEFENSE,
  HALF_BLOOD_DEFENSE,
  MUGGLE_BORN_DEFENSE,
  MUGGLE_DEFENSE,
  SQUIB_DEFENSE,
  BASE_HP,
  RANDOM_HP_BONUS,
  PACK_SIZE,
  SPELL_COUNT,
  CPU_DECK_SIZE,
  DEFAULT_DAMAGE,
  CHARM_DAMAGE,
  CURSE_DAMAGE,
  HEX_DAMAGE,
  JINX_DAMAGE,
  SPELL_DAMAGE,
  TRANSFIGURATION_DAMAGE,
  COUNTER_SPELL_DAMAGE,
  HEALING_DAMAGE,
  SERVER_PORT
}